exports.deployConsumer = require("./deploy.js")
exports.issueRequest = require("./issue.js")
exports.readData = require("./read.js")
exports.requestData = require("./request.js")
exports.update = require("./update.js")
